- name: lookup uuid of cloud
  avi_api_session:
    avi_credentials:
        username: "{{ avi_controller_username }}"
        password: "{{ avi_controller_password }}"
        api_version: "{{ avi_api_version }}"
    controller: "{{ ctrl }}"
    http_method: get
    path: cloud
    tenant: "admin"
    params:
      { name: "{{ CloudName }}" }
  register: aws_cloud
- name: lookup uuid of subnet
  avi_api_session:
    avi_credentials:
        username: "{{ avi_controller_username }}"
        password: "{{ avi_controller_password }}"
        api_version: "{{ avi_api_version }}"
    controller: "{{ ctrl }}"
    http_method: get
    path: networksubnetlist
    tenant: "admin"
    params:
      { name: "{{ aws_subnet }}",
        cloud_uuid: "{{ aws_cloud['obj']['results'][0]['uuid'] }}" }
  register: aws_subnet_uuid
- debug: var=aws_subnet_uuid
- name: Avi Deploy new virtual
  include_role:
    name: avinetworks.aviconfig
  vars:
    cloud_name: "{{ CloudName }}"
    app_name: "{{ ApplicationName.split('.')[0] }}"
    domain_name: "{{ ApplicationName.split('.')[1:] | join('.') }}"
    app_type: "{{ ApplicationType }}"
    avi_controller: "{{ ctrl }}"
    location: "{{ loc }}"
    sni_type: "{{ sni }}"
    department: "{{ Department }}"
    health_monitor: "{{ HealthMonitor }}"
    listening_port: "{{ ListeningPort }}"
    pool_members: "{{  PoolMembers.split('::') }}"
    avi_config_state: "present"
    avi_username: "{{ avi_controller_username }}"
    avi_password: "{{ avi_controller_password }}"
    api_version: "{{ avi_api_version }}"
    tmp_avi_config: "{{ lookup('template','templates/vs_create.j2') | from_yaml }}"
    avi_config: "{{tmp_avi_config.avi_config }}"